openapi: 3.0.1
info:
  title: Default module
  description: ''
  version: 1.0.0
tags: []
paths:
  /users:
    get:
      summary: get users
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    post:
      summary: create user
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              firstName: Rohan
              lastName: Kumar
              email: rohan.kumar1@gmail.com
              password: Password@123
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    patch:
      summary: patch user
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              lastName: Kumar
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /users/create-many:
    post:
      summary: create many users
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: false
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoicm9oYW4ua3VtYXJAZ21haWwuY29tIiwiaWF0IjoxNzkyNTk4NzcyLCJleHAiOjE3OTI2MDIzNzIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.B6LjAmXuXL5lxOyUCHplNnwMKlv6wMNjiMzRD77L79Q
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              users:
                - firstName: Mohan
                  lastName: Kumar
                  email: mohan.kumar@gmail.com
                  password: Password@123
                - firstName: Shyam
                  lastName: Kumar
                  email: shyam.kumar@gmail.com
                  password: Password@123
                - firstName: Karan
                  lastName: Kumar
                  email: karan.kumar@gmail.com
                  password: Password@123
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /posts:
    get:
      summary: Get posts from user
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: startDate
          in: query
          description: ''
          required: false
          example: '2026-10-15T17:39:02.163Z'
          schema:
            type: string
        - name: endDate
          in: query
          description: ''
          required: false
          example: '2026-10-20T17:39:02.163Z'
          schema:
            type: string
        - name: limit
          in: query
          description: ''
          required: false
          example: '10'
          schema:
            type: string
        - name: page
          in: query
          description: ''
          required: false
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    post:
      summary: Create Post
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              title: What's new with NestJS
              postType: post
              slug: new-with-nestjs-5
              status: draft
              content: test-content
              schema: '{}'
              featuredImageUrl: >-
                https://static.vecteezy.com/system/resources/thumbnails/083/933/835/small/beautiful-and-inspiring-picture-detailing-a-bright-hot-air-balloon-over-river-pure-cozy-perfect-for-creatives-moods-stock-image-free-photo.jpeg
              publishOn: '2026-09-23T12:32:00Z'
              metaOptions:
                metaValue: '{"sidebarEnabled": true, "footerActive": true}'
              tags:
                - 1
                - 4
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    patch:
      summary: Update post
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              id: 20
              title: What's new with NestJS with Typescript
              tags:
                - 1
                - 4
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    delete:
      summary: Delete post
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: query
          description: ''
          required: false
          example: '18'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              example:
                message: Cannot DELETE /posts/8
                error: Not Found
                statusCode: 404
          headers: {}
      security:
        - bearer: []
  /meta-options:
    post:
      summary: Create meta-options
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              metaValue: '{"sidebarEnabled": true, "footerActive": true}'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
  /tags:
    post:
      summary: Create Tags
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              name: nestjs
              slug: tech-003
              description: Description-3
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    delete:
      summary: Delete tags
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: query
          description: ''
          required: false
          example: '4'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    get:
      summary: Get all tags
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /tags/soft-delete:
    delete:
      summary: Soft delete tags
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: query
          description: ''
          required: false
          example: '5'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /auth/sign-in:
    post:
      summary: Sign-in
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              email: rohan.kumar@gmail.com
              password: Password@123
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /auth/refresh-tokens:
    post:
      summary: Refresh-token
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              refreshToken: >-
                eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTc5MzAxMjI4NiwiZXhwIjoxNzkzMDk4Njg2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.P0Ja2f_oC1gmF66y7O-IYIzDHROGApMJkjS0GVri3E8
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
components:
  schemas: {}
  responses: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers: []
security:
  - bearer: []
